### ISSUE TITLE
`GetQueryCompletionInformation` get 380 rows, But `NextRowOrError` got EOF

### ISSUE THREAD

**Issue by 1730735794** [Azure/azure-kusto-go#121] opened 2022-10-20 07:06 UTC
my code like this
```
	ctx := context.Background()
	iter, err := client.Query(ctx, datababe, kusto.NewStmt(tableName))
	if err != nil {
		panic("add error handling")
	}
	defer iter.Stop()
	info, err := iter.GetQueryCompletionInformation()
	fmt.Println(info)
	fmt.Println(info.Rows...)
	_, _, err2 := iter.NextRowOrError()
	fmt.Println(err2)
```

I got info by `GetQueryCompletionInformation` : 
```
{{DataTable} 2 QueryCompletionInformation QueryCompletionInformation [{Timestamp datetime} {ClientRequestId string} {ActivityId guid} {SubActivityId guid} {ParentActivityId guid} {Level int} {LevelName string} {StatusCode int} {StatusCodeName string} {EventType int} {EventTypeName string} {Payload string}] [] [[2022-10-20T07:03:21.5530279Z KGC.execute;6fc43e22-5046-469f-865f-cf5b05754740 653274e5-da25-4701-a169-d55eb5d27e90 52ddc8c8-acde-4c39-8092-bb680d9f500c 2ac265a2-e9cb-46a7-8d83-2a54e78ddf52 4 Info 0 S_OK (0) 4 QueryInfo {"Count":1,"Text":"Query completed successfully"}] [2022-10-20T07:03:21.7413073Z KGC.execute;6fc43e22-5046-469f-865f-cf5b05754740 653274e5-da25-4701-a169-d55eb5d27e90 52ddc8c8-acde-4c39-8092-bb680d9f500c 2ac265a2-e9cb-46a7-8d83-2a54e78ddf52 4 Info 0 S_OK (0) 5 WorkloadGroup {"Count":1,"Text":"default"}] [2022-10-20T07:03:21.7413073Z KGC.execute;6fc43e22-5046-469f-865f-cf5b05754740 653274e5-da25-4701-a169-d55eb5d27e90 52ddc8c8-acde-4c39-8092-bb680d9f500c 2ac265a2-e9cb-46a7-8d83-2a54e78ddf52 6 Stats 0 S_OK (0) 0 QueryResourceConsumption {"ExecutionTime":0.4374625,"resource_usage":{"cache":{"memory":{"hits":441,"misses":0,"total":441},"disk":{"hits":0,"misses":0,"total":0},"shards":{"hot":{"hitbytes":0,"missbytes":0,"retrievebytes":0},"cold":{"hitbytes":0,"missbytes":0,"retrievebytes":0},"bypassbytes":0}},"cpu":{"user":"00:00:00","kernel":"00:00:00","total cpu":"00:00:00"},"memory":{"peak_per_node":6292560},"network":{"inter_cluster_total_bytes":1299903,"cross_cluster_total_bytes":0}},"input_dataset_statistics":{"extents":{"total":23,"scanned":23,"scanned_min_datetime":"2022-08-31T06:47:15.7381112Z","scanned_max_datetime":"2022-10-20T04:03:04.9728076Z"},"rows":{"total":380,"scanned":380},"rowstores":{"scanned_rows":0,"scanned_values_size":0},"shards":{"queries_generic":0,"queries_specialized":0}},"dataset_statistics":[{"table_row_count":380,"table_size":387214}],"cross_cluster_resource_usage":{}}]] [] OpQuery}
```
It's obviously that this request accesses the database , and 380 rows of data were scanned.

But `info.Rows...` is empty and i got an err in  `_, _, err2 := iter.NextRowOrError()`, err2 is `EOF`

![image](https://user-images.githubusercontent.com/57705475/196879261-0088c723-19ce-4283-8e29-981f3657ec6d.png)

![image](https://user-images.githubusercontent.com/57705475/196879245-934cc04f-ba44-4d9e-8d98-abad04b6fd4e.png)

**Comment by jesseward** [comment] 2022-10-26 14:14
> But `info.Rows...` is empty and i got an err in `_, _, err2 := iter.NextRowOrError()`, err2 is `EOF`
> ...

hey @1730735794, curious if such a query was working for you at one time? I am seeing something similar on my Kusto DB as of a few days ago.

It looks like the problem is with the statemachine parser logic in `azure-kusto-go`, though I am unable to pinpoint the exact failure scenario (yet).


```go
	ctx := context.Background()
	jsonOut, err := client.QueryToJson(ctx, datababe, kusto.NewStmt(tableName))
	if err != nil {
		panic("add error handling")
	}
	defer iter.Stop()
        fmt.Println(jsonOut)
```

If you run the above, what you see? That `fn` unmarshals the response into `json` instead of the `kusto.RowIterator` type, so it bypasses the logic to decode the Kusto frames. Curious if you see your results (rows) as intended. The header in my JSON response appears as

```json
  {
    "FrameType": "DataSetHeader",
    "IsProgressive": false,
    "Version": "v2.0"
  },
... row data below ...
```

**Comment by 1730735794** [comment] 2022-10-29 15:49
Hey,I've figured out what I'm causing this issue. My server returned an error message in the form `IsProgressive`,In fact, this is also the default query method of kusto-sdk, kusto-sdk will mark a field as version2 to tell the server to expect the server to return with the version2 communication protocol, and the version2 communication protocol is 'IsProgressive', but as you can see, the `IsProgressive` field in the return value is marked as false.&nbsp;


ALL in all, if `Version` in response is 2.0,&nbsp; `IsProgressive` should be true.


So if you didn't marked version of query to version1 by yourself, maybe you can resolve this problem temporaly by&nbsp;


&nbsp; &nbsp; &nbsp;`iter, err := a.client.Query(ctx, a.database, stmt, kusto.CustomQueryOption("results_progressive_enabled", false))`

This query option will marked query as version1, and your kusto-sdk can parse response correctly !


By the way, this is the first time I've received help from a developer from another country, and I'm thrilled and looking forward to helping you more if I can！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Azure/azure-kusto-go"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月26日(星期三) 晚上10:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Azure/azure-kusto-go] `GetQueryCompletionInformation` get 380 rows, But `NextRowOrError` got EOF (Issue #121)





  
But info.Rows... is empty and i got an err in _, _, err2 := iter.NextRowOrError(), err2 is EOF
 ...
  
hey @1730735794, curious if such a query was working for you at one time? I am seeing something similar on my Kusto DB as of a few days ago.
 
It looks like the problem is with the statemachine parser logic in azure-kusto-go, though I am unable to pinpoint the exact failure scenario (yet).
 	ctx := context.Background() 	jsonOut, err := client.QueryToJson(ctx, datababe, kusto.NewStmt(tableName)) 	if err != nil { 		panic("add error handling") 	} 	defer iter.Stop()         fmt.Println(jsonOut)
 
If you run the above, what you see? That fn unmarshals the response into json instead of the kusto.RowIterator type, so it bypasses the logic to decode the Kusto frames. Curious if you see your results (rows) as intended. The header in my JSON response appears as
   {     "FrameType": "DataSetHeader",     "IsProgressive": false,     "Version": "v2.0"   }, ... row data below ...

**Comment by jesseward** [comment] 2022-10-29 16:24
> ALL in all, if `Version` in response is 2.0,&nbsp; `IsProgressive` should be true.

thanks for confirming @1730735794. We had similar findings and have an issue that calls out the  `IsProgressive` header being the culprit as well.

Some notes in https://github.com/Azure/azure-kusto-go/issues/125 , I had used the same work around as well `results_progressive_enabled`, though not sure of the implications.

Hope to hear back from the library owners soon.

**Comment by AsafMah** [comment] 2022-11-06 09:17
Hey, this was an issue with the service.
It should be fixed now in all clusters, if it is still applicable, please comment.

**Closed by AsafMah** 2022-11-06 09:17 UTC
